// English-only display adapter for legacy user data and dynamically created UI labels.
(() => {
  const map = {
    '基本情况':'Basic information','时间与预算':'Dates and budget','住房与办事':'Housing and setup',
    '称呼':'Name','搬去的城市':'Destination city','目前所在城市':'Current city','公司所在城市':'Company city','公司所在区域':'Company district','公司详细位置':'Office location','就业情况':'Employment type',
    '入职时间':'Start date','计划完成搬家时间':'Move deadline','新住处交房日':'New home handover date','开始规划日':'Planning start date','全流程目标完成日':'Overall completion target','可用时间约束':'Availability constraints','一次性搬家预算':'One-time moving budget','每月租房预算':'Monthly rent budget','通勤偏好':'Commute preference',
    '是否接受合租':'Open to shared housing','宠物情况':'Pets','住房偏好':'Housing preferences','当前住房情况':'Current housing','社保情况':'Social insurance','医保情况':'Medical insurance','公积金情况':'Housing provident fund','居住证或落户需求':'Residence permit or household registration','其他已确认需求':'Other confirmed needs',
    '例如：小林':'e.g. Alex','例如：张江高科附近':'e.g. near Zhangjiang Hi-Tech Park','例如：3000元':'e.g. CNY 3,000','例如：3500元/月':'e.g. CNY 3,500/month','例如：旧租约10月20日到期':'e.g. current lease ends October 20','例如：原单位9月缴至月底':'e.g. previous employer paid through the end of September','例如：担心换工作断缴':'e.g. concerned about a coverage gap when changing jobs','例如：需从外地转入':'e.g. transfer from another city','例如：需要办理居住证':'e.g. need to apply for a residence permit','例如：远程办公，需要稳定宽带':'e.g. remote work requires reliable internet',
    '上海市':'Shanghai','上海':'Shanghai','黄浦区':'Huangpu','徐汇区':'Xuhui','长宁区':'Changning','静安区':'Jing’an','普陀区':'Putuo','虹口区':'Hongkou','杨浦区':'Yangpu','浦东新区':'Pudong','闵行区':'Minhang','宝山区':'Baoshan','嘉定区':'Jiading','金山区':'Jinshan','松江区':'Songjiang','青浦区':'Qingpu','奉贤区':'Fengxian','崇明区':'Chongming','张江高科':'Zhangjiang Hi-Tech Park','陆家嘴':'Lujiazui','徐家汇':'Xujiahui','金桥':'Jinqiao',
    '北京市':'Beijing','天津市':'Tianjin','河北省':'Hebei','山西省':'Shanxi','内蒙古自治区':'Inner Mongolia','辽宁省':'Liaoning','吉林省':'Jilin','黑龙江省':'Heilongjiang','江苏省':'Jiangsu','浙江省':'Zhejiang','安徽省':'Anhui','福建省':'Fujian','江西省':'Jiangxi','山东省':'Shandong','河南省':'Henan','湖北省':'Hubei','湖南省':'Hunan','广东省':'Guangdong','广西壮族自治区':'Guangxi','海南省':'Hainan','重庆市':'Chongqing','四川省':'Sichuan','贵州省':'Guizhou','云南省':'Yunnan','西藏自治区':'Tibet','陕西省':'Shaanxi','甘肃省':'Gansu','青海省':'Qinghai','宁夏回族自治区':'Ningxia','新疆维吾尔自治区':'Xinjiang','香港特别行政区':'Hong Kong','澳门特别行政区':'Macao','台湾省':'Taiwan',
    '只需 2 步':'2 steps','下一步':'Next','上一步':'Back','跳过':'Skip','保存并生成计划':'Save and generate plan','发送':'Send','正在为您规划中':'Preparing your plan','正在整理方案…':'Preparing your plan…',
    '这条回答有帮助吗？':'Was this answer helpful?','有帮助':'Helpful','信息不准':'Inaccurate','缺少依据':'Missing evidence','依据与状态':'Evidence and status','信息依据或入口':'Information and entry point','最后追问':'Follow-up questions','目前信息总结':'Summary of current information','近期要完成的事':'Upcoming tasks','事项详情':'Task details','为何':'Why','何时':'When','前置条件':'Prerequisites','完成标准':'Completion standard','请补充':'Please provide','请确认':'Please confirm','需要确认的假设':'Assumptions to confirm','关键假设':'Key assumptions',
    '这一天还没有日程。你可以在助手问答中生成计划。':'There are no events for this day. Ask the assistant to generate a plan.','日期待确认':'Date to be confirmed','日期待核验':'Date to be verified','信息待确认':'Information to be confirmed','官方来源已核验':'Official source verified','知识来源已核验':'Knowledge source verified','样本参考':'Sample reference','挂牌样本':'Listing sample','通勤估算':'Commute estimate','配套待核验':'Amenities pending verification','入口或依据待核验':'Entry point or evidence needs verification','核验时间':'Verified','核验日期':'Verification date',
    '我已记住你的情况：':'I remember your details: ','。可以直接问下一步；信息有变化时告诉我，或到“我的”修改。':'. Ask what to do next, or tell me when something changes. You can also edit it in Profile.','可以先说：入职时间、公司位置、搬家完成时间和一次性搬家预算。通勤、合租与月租预算之后都可以补充。':'Start with your start date, office location, move deadline, and one-time moving budget. You can add commute, shared housing, and monthly rent preferences later.','目前先服务上海。告诉我公司的大致位置，就能开始倒排计划。':'Shanghai is currently supported. Tell me your approximate office location to plan backward from your dates.','日期用来安排先后；搬家预算、通勤、合租和月租预算都可以稍后补充。':'Dates determine task order. You can add moving budget, commute, shared housing, and monthly rent later.',
    '正在整理方案':'Preparing your plan','反馈未同步':'Feedback was not synced','反馈已保存在本机，稍后可重新选择提交。':'Feedback is saved locally. You can submit it again later.','计划暂时没有生成成功，当前资料已保存。请点击发送重试，或补充信息后再次生成。':'The plan was not generated. Your profile is saved; send again to retry or add more information.','暂时无法回答':'Unable to answer for now','重试发送':'Retry','已按确认内容更新计划日历。你可以继续在聊天中调整，新的改动仍会先请你确认。':'The plan calendar was updated as confirmed. You can keep adjusting it in chat; new changes will be shown for confirmation first.','已保留当前日程表，没有应用这次修改。':'The current schedule was kept unchanged.','新增':'Added','修改':'Changed','删除':'Delete','待办事务':'Task','预计期限':'Expected due date','可滑动修改':'Swipe to edit','点击选择日期':'Tap to choose a date','硬截止':'Hard deadline','已保存':'Saved','资料已保存，下次问答会自动使用。':'Profile saved and will be used in future chats.','还没有聊天输入。':'No chat inputs yet.','暂无待提醒的计划':'No plans need reminders','站内已开启':'In-app on','微信未接入':'WeChat not connected','未开启':'Off',
    '请选择':'Please select','省份':'Province','城市':'City','目前所在城市':'Current city','没有匹配的城市':'No matching city','城市数据加载中，请稍后重试。':'City data is loading. Please try again later.','设置“':'Set date for “','确认删除':'Confirm deletion','保存提醒设置':'Save reminder settings','确定清空资料、聊天记录和提醒偏好吗？已确认的计划日历会保留。':'Clear your profile, chat history, and reminder preferences? Confirmed calendar events will remain.','本机存储空间不足':'This browser is out of storage space','请稍后重试':'Please try again later','入职':'Start date','取消':'Cancel','确认':'Confirm','已记录':'profile item(s) saved','· ':'· ','存储不足':'out of storage','本地演示模式':'Local demo mode','GPT 已连接':'LLM connected','尚未配置大模型':'No language model configured','无法连接服务':'Unable to connect to the service','这一天还没有日程':'There are no events for this day','可滑动修改':'Swipe to edit','点击选择日期':'Tap to choose a date','删除':'Delete','新增':'Added','修改':'Changed','待办事务':'Task','预计期限':'Expected due date','站内提醒':'In-app reminder','未设置':'Not set','已选择':'selected','其中删除':'including','项':'','硬截止改动需核验':'A hard deadline change requires verification','我已核实以上硬截止允许修改或删除，仍要按新日程保存':'I verified the hard deadline change and still want to save the proposed schedule','确认删除所选计划':'Confirm deletion','需要，更新计划日历':'Yes, update my calendar','不需要改动当前日程表':'Keep my calendar unchanged','请填写起始日期、终止日期和事件描述':'Enter a start date, end date, and event description','终止日期不能早于起始日期':'The end date cannot be earlier than the start date','日程已达到 40 项上限':'The calendar has reached its 40-event limit','本机存储空间不足':'This browser is out of storage space','保存并生成计划':'Save and generate plan','保存提醒设置':'Save reminder settings','已保存':'Saved','确定清空资料':'Clear your profile',
    '公司位置或办公枢纽':'Office location or transit hub','例如：张江高科、陆家嘴':'e.g. Zhangjiang Hi-Tech Park or Lujiazui','希望完成搬家的时间':'Desired move completion date','先确定目的地':'Choose your destination','把时间和预算放进来':'Add your dates','搬去的城市  ·  上海':'Destination city · Shanghai'
  };
  function translate(value) {
    let out = String(value || '');
    for (const key of Object.keys(map).sort((a,b) => b.length - a.length)) out = out.split(key).join(map[key]);
    out = out.replace(/(\d{4})年/g,'$1').replace(/(\d{1,2})月/g,'$1').replace(/(\d{1,2})日/g,'$1').replace(/(\d+)分钟内/g,'within $1 min').replace(/(\d+)-(\d+)分钟/g,'$1–$2 min').replace(/两小时以内/g,'within 2 hours').replace(/随便/g,'Flexible').replace(/应届生首次就业/g,'First job after graduation').replace(/跨城市换工作/g,'Changing jobs across cities').replace(/不接受合租/g,'Not open to shared housing').replace(/接受合租/g,'Open to shared housing').replace(/没有宠物|不养宠物|无宠物/g,'No pets').replace(/元\/月/g,' CNY/month').replace(/元/g,' CNY');
    return /[\u3400-\u9fff]/.test(out) ? 'Saved detail' : out;
  }
  window.englishDisplay = translate;
  function walk(node) {
    if (node.nodeType === Node.TEXT_NODE) {
      const parent = node.parentElement;
      if (parent?.closest('#chat-input, #profile-fields input, #profile-fields textarea, #picker-search')) return;
      let text = node.nodeValue;
      if (/^[\s\u200b]*$/.test(text)) return;
      if ((parent?.closest('.row.user') || parent?.closest('.history-item')) && /[\u3400-\u9fff]/.test(text)) text = 'User message submitted in Chinese';
      const result = translate(text);
      const display = parent?.closest('.row.assistant .bubble') && /[\u3400-\u9fff]/.test(result) ? 'Earlier assistant response in Chinese' : result;
      if (display !== node.nodeValue) node.nodeValue = display;
    } else if (node.nodeType === Node.ELEMENT_NODE && !['SCRIPT','STYLE'].includes(node.tagName)) {
      for (const attr of ['aria-label','placeholder','title']) if (node.hasAttribute(attr)) node.setAttribute(attr, translate(node.getAttribute(attr)));
      for (const child of node.childNodes) walk(child);
    }
  }
  const apply = () => walk(document.body);
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', apply, {once:true}); else apply();
  new MutationObserver(apply).observe(document.documentElement,{childList:true,subtree:true});
})();
